[build]
  publish = "dist" # 또는 build 등, Netlify에 배포할 폴더 이름
  command = "yarn build" # CRA가 아닌 Webpack 직접 구성이라면 이 빌드 명령어 그대로 사용

[build.environment]
  SECRETS_SCAN_ENABLED = "false"  # 시크릿 감지 끄기

[[redirects]]
  from = "/images/*"
  to = "/images/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  