export const SPOTIFY_BASE_URL = process.env.SPOTIFY_BASE_URL;
export const REDIRECT_URI_LOCAL =
  process.env.REACT_APP_SPOTIFY_REDIRECT_URI_LOCAL;
export const REDIRECT_URI_PROD =
  process.env.REACT_APP_SPOTIFY_REDIRECT_URI_PROD;
